### ISSUE TITLE
Can't add an extra user

### ISSUE THREAD

**Issue by acienfuegos** [StepanyanAlbert/djangoyoutube#1]
Hi there!

First of all, thanks for the tutorial, it is very interesting!

Just for adding, one thing, and maybe you know it. 

The code is working perfect, for addind an admin, from console mode, but it's not working if you want to add an extra user (I mean a normal one)

I couldn't find, the issue, yet (not time enough) but just as an alert :)

Thanks again for your work!

**Comment by StepanyanAlbert** [comment]
Hello Dear  @acienfuegos !! Thansk for this alert ) :dancing_men:  I will try to fix it as soon as possible .(same problem with time ))) . )

**Comment by acienfuegos** [comment]
You're welcome! 

If I find it, I will write here, I think, that should be something to move from True to False, or something like that... but I need to check!

Thanks for your fast answer :)

**Comment by StepanyanAlbert** [comment]
:accept:  Very  glad that it helps ! Yep it would be very nice, so we can share  :)

**Comment by acienfuegos** [comment]
Hi!

Just found the problem, it was something with the captcha package, I don't have enough time to check, how to introduce it, but if you comment in **admin.py** "the captcha line":

```
class UserCreationForm(forms.ModelForm):
        password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
        password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'confirm password'}))
        #captcha = MathCaptchaField()
```

You could add, extra users with problems :)

**Comment by StepanyanAlbert** [comment]
Hello . So If it is right in that case you can not use captcha field? I will manage to fix this on this weekend . @acienfuegos Thank you for taking time ;)

**Comment by gevorgm** [comment]
:+1:

**Comment by acienfuegos** [comment]
Right @StepanyanAlbert 

You're welcome ;-)

**Comment by akash-codes93** [comment]
Are there any update on the captcha field??

**Comment by akash-codes93** [comment]
Hello, 
I found the answer

In the UserAdmin(BaseUserAdmin) class

the line

            'fields': ('email', 'date_of_birth', 'password1', 'password2','captcha' )}


'captcha' has to be added.

**Comment by StepanyanAlbert** [comment]
Hello @akash-github-projects thanks for submission 
Already commited  https://github.com/StepanyanAlbert/djangoyoutube/commit/3ab1cbc1c75b2e394b852c965a73b74a84875839 ))))
Let me know if it you got any questions
